LIST(INSERT JavaScriptCore_INCLUDE_DIRECTORIES 0
    "${BLACKBERRY_THIRD_PARTY_DIR}/icu"
)

LIST(APPEND JavaScriptCore_SOURCES
    DisassemblerARM.cpp
)

#ADD_DEFINITIONS(-DINST_VMOVD=1)
#ADD_DEFINITIONS(-DOPT_DEAD_CODE=1)
#ADD_DEFINITIONS(-DOPT_FASTACCESS=1)
#ADD_DEFINITIONS(-DINST_CMN=1)
#ADD_DEFINITIONS(-DINST_LDRD=1)
#ADD_DEFINITIONS(-DINST_STRD=1)
#ADD_DEFINITIONS(-DOPT_SCHED=1)

#FIXME: We need to fix the relative path here
INSTALL(FILES "wtf/Forward.h" DESTINATION ../../usr/include/browser/webkit/wtf)
